openapi: '3.0.2'
info:
  title: GsStartApp
  description: IntranetApp for staffs
  version: '1.0'
servers:
  - url: https://api.server.test/v1
    description: プロダクション API
  - url: http://{host}:{port}/api/v0
    description: 開発用
    variables:
      host:
        default: localhost
      port:
        default: '8080'
paths:
  /auth/signin:
    post:
      summary: Login by loginId and Password.
      requestBody: # ポストするオブジェクト
        content:
          application/json:
            schema:
              type: object
              properties:
                login_id:
                  type: string
                  example: "test_user"
                password:
                  type: string
                  example: "test_user123!"
      responses:
        '200': # HTTP status
          description: Returns a single Object
          content:
            application/json: # レスポンスの形式指定
              schema: 
                type: object
                properties:
                  token:
                    type: string
                    example: JsonWebToken
                  staffId:
                    type: integer
                    example: 1
                  loginId:
                    type: string
                    example: admin8080
                  role:
                    type: integer
                    example: ROLE_ADMIN
                  expire:
                    type: integer
                    example: 180000000
  /staffs:
    get:
      summary: Get all staffs.
      description: Returns an array of Staff model
      responses:
        '200': # HTTP status
          description: A JSON array of Staff entity
          content:
            application/json: # レスポンスの形式指定
              schema: 
                type: array
                example: # サンプルデータ
                  - id: 1
                    name: John Doe
                  - id: 2
                    name: Jane Doe
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                mail_address:
                  type: string
                  example: "test@example.com"
                login_id:
                  type: string
                  example: "test_user"
                password:
                  type: string
                  example: "test_user123!"
      responses:
        '204':
          description: OK
  /staffs/{staff_id}:
    delete:
      parameters:
        - in: path
          name: staff_id
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: OK
  /staffs/{staff_id}/basic_info:
    get:
      parameters:
        - in: path
          name: staff_id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
    put:
      parameters:
        - in: path
          name: staff_id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
  /staffs/{staff_id}/detail_info:
    get:
      parameters:
        - in: path
          name: staff_id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
    put:
      parameters:
        - in: path
          name: staff_id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
  /attendances:
    get:
      parameters:
        - in: query
          name: yearMonth
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
    post:
      responses:
        '200':
          description: OK
